Adding archive message
GoogleCloudPlatform/pubsubbeat pull request #47
Opened 2020-06-18 17:11 UTC by josephlewis42

Updating README with archive message prior to sending to github.com/googlearchive

2020-06-18 17:22 UTC, SuperQ approved these changes
LGTM

2020-06-19 14:59 UTC, evandbrown requested changes

2020-06-19 14:59 UTC, evandbrown commented on README.md
> +This project is no longer actively maintained by Google.
Please add "For assistance, please reach out to the Google Open Source Programs Office." to this paragraph.

2020-06-19 15:02 UTC, evandbrown approved these changes

2020-06-19 15:02 UTC, merged